#!/bin/bash 
#SBATCH --job-name="BenchA_CPU" 
#SBATCH --output="cpu.out" 
#SBATCH --partition=gpu 
#SBATCH --nodes=1 
#SBATCH --gres=gpu:k80:4 
#SBATCH -t 48:00:00 

numNeuron='1000 3160 10000 31600 100000 316000'
numPartitionCPU='8 4 2 1'
file="cpu.csv"

echo "CPU" >> $file 
for numP in $numPartitionCPU
do
	echo $numP "partition" >> $file
	for numN in $numNeuron
	do
		./benchmarkA $numN 1 20 50  1.7 1.5 2.0 $file 42 100 $numP 0
	done
done

#1. number of neurons(num_exc+num_inh)  2. simulate time; 3. input  fire rates; 4. weight from input to exc; 5. weight from exc to inh 6. weight from inh to exc; 7.weight from exc to exc  8. recordfile; 9. randseed; 10. number of synapse per neuron; 11. number of partitions; 12. backend
