# CARLsim Makefile
# CARLsim available from http://socsci.uci.edu/~jkrichma/CARLsim/
# Ver 11/01/2013

# source files of the sim core
SOURCES = snn_cpu.cpp mtrand.cpp PropagatedSpikeBuffer.cpp printSNNInfo.cpp gpu_random.cu snn_gpu.cu
DEP = snn.h PropagatedSpikeBuffer.h errorCode.h config.h gpu_random.hpp
LIBCUTIL = -lcutil_x86_64

test_issue8: ${SOURCES} ${DEP} test/test_issue8.cpp
	nvcc -I${NVIDIA_SDK}/C/common/inc/ -L${NVIDIA_SDK}/C/lib ${LIBCUTIL} -arch sm_13 ${SOURCES} test/test_issue8.cpp -o test_issue8

test_issue9: ${SOURCES} ${DEP} test/test_issue9.cpp
	nvcc -I${NVIDIA_SDK}/C/common/inc/ -L${NVIDIA_SDK}/C/lib ${LIBCUTIL} -arch sm_13 ${SOURCES} test/test_issue9.cpp -o test_issue9
