#!/bin/bash
#SBATCH --job-name="bmark3-1"
#SBATCH --output="result1.out"
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --gres=gpu:k80:4
#SBATCH -t 48:00:00

module load cuda/7.0

numNeurons='10000'
numSynapses=(100 200 300 400 500 600)
numCore='4'
index='0'
weight1=(3.75 2.0586 1.4375 1.0938 0.875 0.75)
weight2=(3.5703 1.9609 1.339 1.0 0.8125 0.6687)
weight3=(3.25 1.4268 0.8652 0.5625 0.4609 0.375)
filename="r1.csv"
for numC in $numCore
do
	echo "GPU number is " $numC >> $filename
	for numN in $numNeurons # number of neurons, which defines the workload
	do
		for n in $index # number of synapse per neuron
		do
			./benchmark3 $numN 100 42 ${numSynapses[$n]} $filename 1 20 80 ${weight1[$n]}  ${weight2[$n]} ${weight3[$n]} $numC 0
			#13 parameters needed
			#1, number of neurons in a group | 2, number of input neurons
			#3, randseed | 4, number of synapse per neuron |5, record File
			#6, number of simulate time |7, input fire rate 
			#8, connection weight from input to exc1
			#9, connection weight from exc1 to exc2	
			#10, connection weight from exc2 to exc3
			#11, connection weight from exc3 to exc4
			#12, number of GPU cores | 13, whether need weight tuning		
		done
	done	
done


